### ISSUE TITLE
Issue while using salesforce volos-connectors. 

### ISSUE THREAD

**Issue by aakankshaBadola** [apigee-127/volos-connectors#15]
I am getting the following error:--

{
    "fault": {
        "faultstring": "Script node executed prematurely: Error: Cannot find module 'volos-salesforce'\nError: Cannot find module 'volos-salesforce'\n    at module.js:340:0\n    at module.js:280:0\n    at module.js:364:0\n    at require (module.js:380:0)\n    at /organization/environment/api/server-express.js:1:0\n    at module.js:456:0\n    at module.js:474:0\n    at module.js:356:0\n    at module.js:312:0\n    at module.js:497:0\n    at startup (trireme.js:142:0)\n    at trireme.js:923:0\n",
        "detail": {
            "errorcode": "scripts.node.runtime.ScriptExitedError"
        }
    }
}

I am getting this error when, I am using salesforce volos-connectors without avault. I am referring to this link... https://github.com/apigee-127/volos-connectors/tree/master/volos-salesforce

**Comment by RVAGH** [comment]
Did you npm and download the volos-salesforce ?
